### ISSUE TITLE
I am looking forward to discussing with you

### ISSUE THREAD

**Issue by ntucschen** [kamilkk852/vb-tracking#1]
I am very interested in your topic and the program.
1. Can you give me a complete example that how to use your program ?
2. Do you have references to other paper or method?
This is my email: r06548051@g.ntu.edu.tw
I am looking forward to discussing with you. 

Best Regards,

**Comment by kamilkk852** [comment]
1. Not yet. The system is still in the early developing phase, accuracy is still far from being good, but I'm working on it.
2. The project is partially based on the YOLO (You Only Look Once) algorithm and this is the only related paper at the moment.
